name: simurgh_cli
description: Reproducible toolchain and release baseline tools for simurgh.
version: 0.1.0-dev.1
publish_to: none
environment:
  sdk: '>=3.12.2 <3.13.0'
dependencies:
  args: 2.7.0
  crypto: 3.0.7
  path: 1.9.1
dev_dependencies:
  test: 1.31.0
executables:
  simurgh: simurgh
